### ISSUE TITLE
Error in `find_tool_by_name` if statement? 

### ISSUE THREAD

**Issue by littlewatkins** [NRL-Plasma-Physics-Division/turbopy#110]
**Question**
*In `core.py`, inside the `Simulation` class, there is a function `find_tool_by_name`. The body is:*  
`tools = [t for t in self.compute_tools if t.name == tool_name]`  
`if len(tools) == 1:`  
&emsp; `return tools[0]`  
`return None`

The way it's currently written, it will return `None` regardless of the length of `tools`, at least in a quick like-for-like test.
![image](https://user-images.githubusercontent.com/35573848/89208389-db99ab00-d581-11ea-9268-a0e42d590435.png)

*Should there be an `else` with the `return None`?*

*I haven't tested it within turboPy yet.* 
But I want to check before fixing it, in case it's not really suppose to be fixed.

**Comment by arichar6** [comment]
First, in your statement `In[3]` on line 4, you should have `print(tryingagain)` instead of `print(trying)`.

In the section `In[1]`, the return statement on line 4 will exit the function before getting your line 5. It ends up giving the same behavior as if you put the line `return None` within an else block.

**Comment by littlewatkins** [comment]
🤦‍♂️ 🤦‍♂️  Guess I should have created a test for my test... how embarrassing. And probably thought more than 10 seconds about the return order lol
