### ISSUE TITLE
Does CSVDiagnosticOutput only handle 1D arrays?

### ISSUE THREAD

**Issue by padamson** [NRL-Plasma-Physics-Division/turbopy#23]
Does the CSVDiagnosticOutput class in diagnostics only handle 1D arrays? (It appears so.)

If so, should it be rewritten to handle 1D or 2D numpy arrays?

**Comment by arichar6** [comment]
The `CSVDiagnosticOutput` class can be used for 0D data (like a "trace" of a value vs time), or for 1D data vs time. As written, it can't output anything higher, e.g., 2D arrays vs time because it uses the numpy `savetxt` function which is limited to 2D data.

I like the idea of allowing higher dimensional output, but maybe csv is not a good format for that.

**Comment by padamson** [comment]
Agree CSV is probably not the right format for higher dimension data.
