### ISSUE TITLE
What's the deal with commits? 

### ISSUE THREAD

**Issue by AOstenfeld** [NRL-Plasma-Physics-Division/turbopy#74]
**Question**
*What happens when two different commits are made to the same version of a file? I've been writing some tests for the core.py file, but as of writing this comment, @gracetangg is also writing tests, and I noticed that we are both working from the much shorter version of the test_core.py file that is on the main repo. I want to keep writing tests, but I don't know if that will create conflicts with the pull requests that have not yet been committed to the main turbopy repo.*

**Comment by GarethTMorgan** [comment]
To my knowledge, if you're working on separate tests (tests for different things) then GitHub shouldn't have a large issue. It might have a complaint about line numbers being off but that's easily fixable. Usually, big problems occur when two people edit the same line of code or a file is deleted while another person edits the same file. Admins may have a better idea of how to resolve the conflicts, but that's my knowledge so far @AOstenfeld .

**Comment by arichar6** [comment]
That's a great question. There are several things that can happen in a case like this. The main thing that we would like to avoid is having two people work on the same parts of the same file simultaneously, since that leads to duplication of effort. In the case you describe, you are both writing tests in the same file, but the tests are for different parts of `core.py`.

In this case, you can both make PRs from your dev branch to main. I will look at (and test) the code in your PR, and then merge. Here, I've merged @gracetangg's PR, and requested a few changes to yours. Once you've made those changes, I will approve your PR. Then, before I merge it to main, I will resolve any potential conflicts between your submission and the main branch. Once I resolve those, I can merge your PR to main.

Side note, by "resolve merge conflicts" I mean that I will look at the code, and take the lines that I want from each file. Then I make a new commit with the lines that I want, and use that when merging your contribution into main.

This is a bit hard to explain in words, so I'd be happy to do a call sometime and explain. Or we can discuss either in this afternoon's call, or the meeting on Wed morning.

**Comment by arichar6** [comment]
@AOstenfeld if these answers help, then go ahead and close this issue.
